import type React from 'react';
import type { Metadata } from 'next';
import '@/styles/styles.css';
import { AuthProvider } from '@/contexts/auth-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  generator: 'v0.dev',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <AuthProvider>
          <div className='flex-grow'>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
